name: django
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h0281608_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - asgiref=3.11.0=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h03d9500_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cryptography=46.0.3=py311h8488d03_0
  - django=5.2.8=pyhd8ed1ab_0
  - frozenlist=1.7.0=py311h52bc045_0
  - google-ai-generativelanguage=0.6.15=pyhd8ed1ab_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-generativeai=0.8.5=pyh29332c3_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - grpcio=1.71.0=py311h8825b61_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_12
  - libgcc-ng=15.2.0=h69a702a_12
  - libgomp=15.2.0=he0feb66_12
  - libgrpc=1.71.0=h8e591d7_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libprotobuf=5.29.3=h7460b1f_2
  - libre2-11=2025.06.26=hba17884_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h934c35e_12
  - libstdcxx-ng=15.2.0=hdf11a46_12
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - multidict=6.6.3=py311h2dc5d0c_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - propcache=0.3.1=py311h2dc5d0c_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.29.3=py311h3a6f5f3_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h902ca64_1
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hd63d673_2_cpython
  - python_abi=3.11=8_cp311
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - re2=2025.06.26=h9925aae_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yarl=1.22.0=py311h3778330_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - anyio==4.12.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - google-genai==1.52.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.6
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pillow==12.0.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - psutil==7.1.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - scipy==1.16.3
      - tenacity==9.1.2
      - ultralytics==8.3.233
      - ultralytics-thop==2.0.18
      - websockets==15.0.1
prefix: /home/admin1/.conda/envs/django
